// Copyright (C) 2023 owoDra

#pragma once

#include "ViewModeTypes.generated.h"


/**
 * Blend function used to transition between ViewModes
 */
UENUM(BlueprintType)
enum class EViewModeBlendFunction : uint8
{
	Linear,
	EaseIn,
	EaseOut,
	EaseInOut,

	COUNT	UMETA(Hidden)
};


/**
 * Activation state of ViewMode
 */
UENUM(BlueprintType)
enum class EViewModeActivationState : uint8
{
	// State during blending before becoming active
	PreActivate,	

	// State activated
	Activated,	

	// State during blending before deactivation
	PreDeactevate,	

	// State deactivated
	Deactevated,	

	COUNT	UMETA(Hidden)
};


/**
 * Data generated by the ViewMode used to blend the ViewMode
 */
struct FViewModeInfo
{
public:
	FViewModeInfo();

public:
	FVector Location;
	FRotator Rotation;
	FRotator ControlRotation;
	float FieldOfView;

public:
	void Blend(const FViewModeInfo& Other, float OtherWeight);

};
